9.0 backport ir attachment s3 (#464)
* [ADD] ir_attachment_s3, ir_attachment_url (it-projects-llc/addons-dev#161)

* [ADD] ir_attachment_s3, ir_attachment_url (it-projects-llc/addons-dev#161)

* [DOC] ir_attachment_url and ir_attachment_s3

* [DOC] ir_attachment_url and ir_attachment_s3

* [FIX] ir_attachment_s3: don't raise error if credentials are not specified

We use INFO level because it's not an error.

* [IMP]  ir_attachment_s3: s3 credentials from os environment (#325)

* [DOC] fix formattng

* [DOC] add --log-handler note

* [FIX] ir_attachment_url: don't write url for assets if their type is … (#329)

* [FIX] ir_attachment_url: don't write url for assets if their type is 'url'

* [FIX] write returns True

* [ADD] ir_attachment_s3: use os_var_name with s3 condition also

* [ADD] ir_attachment_s3: depends on ir_attachment_url, filter protected attachments (#331)

* [ADD] ir_attachment_s3: depends on ir_attachment_url, filter protected attachments (#331)

* [DOC] ir_attachment_s3 improvement

* [LINT] unused imprort

* [DOC] don't use header in changelog.rst

* [DOC] don't use header in changelog.rst

* [ADD] ir_attachment_s3: logger message on param creation

* [FIX] ir_attachment_s3: don't show env in logs show only env name

* [ADD] The ability to specify images URL from interface directly (#410)

* [ADD] Added the ability to Specify images URL from interface directly

* [FIX] Fixes lint errors

* [FIX] Fixes lint error

* [10.0] ir_attachment_url [ADD] the ability to specify images URL from interface directly; url validation function [FIX] images are displayed in kanban view correctly (#413)

* [ADD] Added the ability to Specify images URL from interface directly

* [FIX] Fixes lint errors

* [FIX] Fixes lint error

* [FIX] Fixes the URL validation function, Fixes small and medium image errors

* [FIX] Fixes lint errors

* [DOC] Updated usage instruction

* [DOC] Updated changelog and module version

* [REF] Refactoring code

* [FIX] Fixes patch monkey error, using post_load parameter

* [FIX] Fixes post_load parametererror for binary field

* [IMP][10.0] ir_attachment_s3  improvement: ability to upload existing images (#432)

* [IMP] ir_attachment_s3: s3 condition in the form of search domain

* [ADD] ir_attachment_s3: menu for s3 settings

* [ADD] ir_attachment_s3: add button for upload existing attachments on s3 settings form

* [REF] ir_attachment_s3: shorter version of get_default_

* [FIX] ir_attachment_s3: allow empty condition - upload all attachments on s3

* [DOC] ir_attachment_s3

* [DOC] index.html: update s3 condition

* Translation Bot updated translations from Transifex

* [FIX] Technical error related to saving URL

* [DOC] clarify fixed error

* [DOC] ir_attachment_s3: updates in index.html and new version

* [DOC] fix spelling

* [MOV] ir_attachment_url: ready

* [MOV] ir_attachment_s3: ready

* [BACKPORT] ir_attachment_url, ir_attachment_s3

* [FIX] ir_attachment_s3: this is how it was in 9.0 `res.config.settings`

* [BACKPORT] ir_attachment_s3: how it was in 9.0

* [CI] requirements: boto3 for ir_attachment_s3

* [BACKPORT] ir_attachment_s3: @api.multi was mandatory in 9

* [BACKPORT] fix styles for 9.0

* [BACKPORT] fix write function for 9.0

* [FIX] lint errors

* [FIX] lint errors

* [BACKPORT] ir_attachment_url: there was _data_get instead of _compute_datas in 9.0

* [REF] don't use direct import to avoid travis warnings

* [FIX] ids is not defined

  File "/mnt/odoo-extra/runbot/static/build/09088-464-2910d8/openerp/addons/ir_attachment_url/models/ir_attachment.py", line 13, in _data_set
    return super(ir_attachment, self)._data_set(cr, uid, ids, name, arg, context=context)
ParseError: "global name 'ids' is not defined" while parsing /mnt/odoo-extra/runbot/static/build/09088-464-2910d8/openerp/addons/website/data/data.xml:87, near
<record id="menu_website" model="ir.ui.menu">
            <field name="name">Website</field>
            <field name="sequence" eval="200"/>
            <field name="web_icon">website,static/description/icon.png</field>
            <field name="action" ref="action_website"/>
        </record>
2017-09-26 18:48:16,648 25740 CRITICAL 09088-464-2910d8-a

* [FIX] wrong import. Need more osv

* [FIX} ir_attachment_s3: _data_set() takes at least 7 arguments

* [CI] ir_attachment_url: test _data_get

* [CI] ir_attachment_url: test `url` type attachments

* [CI] ir_attachment_url: typo in tests

* [CI] ir_attachment_url: No such file or directory: '/mnt/data-dir/filestore..'

* [CI] ir_attachment_url: cover ir_attachment.py

* [CI] ir_attachment_url: cover ir_http.py

* [LINT] ir_attachment_url: flake8

* [LINT] ir_attachment_url: pylint

* [FIX] ir_attachment_url: maximum recursion depth exceeded

* [BACKPORT] ir_attachment_s3: use old api `_data_set` instead of 10.0 `_inverse_datas`

* [FIX] ir_attachment_s3: the case if s3 parameters are not set

* [IMP] ir_attachment_s3: rem unnecessary if

* [LINT] ir_attachment_s3