[FIX] don't create partner explicitly, because it could lead
to error, e.g. when user sends unknown lang setting.

LOG:

2017-02-13 07:23:46,470 11825 INFO 03108-8-0-6561a0-base werkzeug: 127.0.0.1 - - [13/Feb/2017 07:23:46] "GET /web/session/logout HTTP/1.0" 303 -
2017-02-13 07:23:46,554 11825 INFO 03108-8-0-6561a0-base werkzeug: 127.0.0.1 - - [13/Feb/2017 07:23:46] "GET /web HTTP/1.0" 200 -
2017-02-13 07:23:47,139 11825 INFO 03108-8-0-6561a0-base werkzeug: 127.0.0.1 - - [13/Feb/2017 07:23:47] "GET /web/login?redirect=http%3A%2F%2F03108-8-0-6561a0-base.runbot.it-projects.info%2Fweb%3F HTTP/1.0" 200 -
2017-02-13 07:23:48,946 11825 INFO 03108-8-0-6561a0-base werkzeug: 127.0.0.1 - - [13/Feb/2017 07:23:48] "GET /web/signup?redirect=http%3A%2F%2F03108-8-0-6561a0-base.runbot.it-projects.info%2Fweb%3F HTTP/1.0" 200 -
2017-02-13 07:24:00,977 4579 INFO ? openerp.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections to 'host=172.17.0.3 port=5432 user=odoo password=xxxx dbname=03108-8-0-6561a0-base'
2017-02-13 07:24:01,197 4579 INFO 03108-8-0-6561a0-all openerp.modules.loading: loading 1 modules...
2017-02-13 07:24:01,289 4579 INFO 03108-8-0-6561a0-all openerp.modules.loading: 1 modules loaded in 0.09s, 0 queries
2017-02-13 07:24:01,633 4579 INFO 03108-8-0-6561a0-all openerp.modules.loading: loading 164 modules...
2017-02-13 07:24:01,930 4579 INFO 03108-8-0-6561a0-all openerp.modules.loading: 164 modules loaded in 0.30s, 0 queries
2017-02-13 07:24:02,864 11825 INFO 03108-8-0-6561a0-base werkzeug: 127.0.0.1 - - [13/Feb/2017 07:24:02] "POST /web/signup?redirect=http%3A%2F%2F03108-8-0-6561a0-base.runbot.it-projects.info%2Fweb%3F HTTP/1.0" 500 -
2017-02-13 07:24:03,035 11825 ERROR 03108-8-0-6561a0-base werkzeug: Error on request:
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 193, in run_wsgi
execute(self.server.app)
File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 181, in execute
application_iter = app(environ, start_response)
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/service/wsgi_server.py", line 216, in application
return application_unproxied(environ, start_response)
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/service/wsgi_server.py", line 202, in application_unproxied
result = handler(environ, start_response)
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/http.py", line 1297, in __call__
return self.dispatch(environ, start_response)
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/http.py", line 1271, in __call__
return self.app(environ, start_wrapped)
File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 599, in __call__
return self.app(environ, start_response)
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/http.py", line 1444, in dispatch
result = ir_http._dispatch()
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/addons/crm/ir_http.py", line 13, in _dispatch
response = super(ir_http, self)._dispatch()
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/addons/base/ir/ir_http.py", line 175, in _dispatch
return self._handle_exception(e)
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/addons/base/ir/ir_http.py", line 145, in _handle_exception
return request._handle_exception(exception)
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/http.py", line 673, in _handle_exception
return super(HttpRequest, self)._handle_exception(exception)
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/addons/base/ir/ir_http.py", line 171, in _dispatch
result = request.dispatch()
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/http.py", line 691, in dispatch
r = self._call_function(**self.params)
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/http.py", line 317, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/service/model.py", line 118, in wrapper
return f(dbname, *args, **kwargs)
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/http.py", line 314, in checked_call
return self.endpoint(*a, **kw)
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/http.py", line 810, in __call__
return self.method(*args, **kw)
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/http.py", line 410, in response_wrap
response = f(*args, **kw)
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/addons/auth_signup_confirmation/controllers/auth_signup_confirmation.py", line 38, in web_auth_signup
res = self._singup_with_confirmation(*args, **kw)
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/addons/auth_signup_confirmation/controllers/auth_signup_confirmation.py", line 76, in _singup_with_confirmation
'email': kw['login'],
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/api.py", line 266, in wrapper
return new_api(self, *args, **kwargs)
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/addons/base/res/res_partner.py", line 577, in create
partner = super(res_partner, self).create(vals)
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/api.py", line 266, in wrapper
return new_api(self, *args, **kwargs)
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/api.py", line 508, in new_api
result = method(self._model, cr, uid, *args, **old_kwargs)
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/addons/mail/mail_thread.py", line 381, in create
thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/api.py", line 268, in wrapper
return old_api(self, *args, **kwargs)
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/api.py", line 372, in old_api
result = method(recs, *args, **kwargs)
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/models.py", line 4104, in create
record = self.browse(self._create(old_vals))
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/api.py", line 266, in wrapper
return new_api(self, *args, **kwargs)
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/api.py", line 508, in new_api
result = method(self._model, cr, uid, *args, **old_kwargs)
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/models.py", line 4230, in _create
self._check_selection_field_value(cr, user, field, vals[field], context=context)
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/api.py", line 268, in wrapper
return old_api(self, *args, **kwargs)
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/api.py", line 372, in old_api
result = method(recs, *args, **kwargs)
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/models.py", line 2263, in _check_selection_field_value
field.convert_to_cache(value, self)
File "/mnt/odoo-extra/runbot/static/build/03108-8-0-6561a0/openerp/fields.py", line 1431, in convert_to_cache
raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for res.partner.lang: 'ru_RU'
127.0.0.1 - - [2017-02-13 07:24:04] "POST /longpolling/poll HTTP/1.0" 200 305 50.124297
2017-02-13 07:24:04,763 4579 INFO 03108-8-0-6561a0-all openerp.modules.loading: Modules loaded.
2017-02-13 07:24:04,871 4579 INFO ? openerp.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 3 connections to 'host=172.17.0.3 port=5432 user=odoo password=xxxx dbname=03108-8-0-6561a0-all'